name: CI for MCDR Plugin

on:
  push:
  pull_request:

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pack Plugin
      run: |
        mkdir package
        python -m mcdreforged pack -o ./package

    - uses: actions/upload-artifact@v2
      with:
        name: QuickBackupM package for ${{ github.sha }}
        path: package/
